version: "3.8"

services:
  build:
    image: silkeh/clang:14
    container_name: hela3D.build
    working_dir: /srv/hela3D

    command:
    - /bin/bash
    - -c
    - |
      cd .build 
      cmake .. 
      cmake --build .

    volumes:
    - .:/srv/hela3D

  run:
    image: silkeh/clang:14
    container_name: hela3D.run
    working_dir: /srv/hela3D/.build

    command:
    - /bin/bash
    - -c
    - |
      cmake .. 
      cmake --build .
      cd bin && ./hela3D.Console

    volumes:
    - .:/srv/hela3D


